name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["12", "14"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - run: npm ci
      - run: npm test

  # The "test" step can be required in branch protection and does not
  # change each time the test matrix changes.
  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - run: echo ok
